spring:
  http:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 1024Mb
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  mvc:
    view:
      prefix:
      suffix: .jsp
  profiles:
    active: prod
    include:
server:
  tomcat:
    basedir: logs
  port: 80